perf: allow pre-allocate of size when new map
elliotchance/orderedmap pull request #48
Opened 2024-11-29 04:06 UTC by VarusHsu

There is a simple result from the bench test:
|entries|withInitialedSize|withoutInitialedSize|rate|
|-------|------|----|---|
| 1e3 | 41153 ns/op  | 72909 ns/op | 56.44% |
|1e5 | 7523395 ns/op | 9731575 ns/op | 77.31% |
|1e7 | 2005930041 ns/op | 2555268041 ns/op | 78.50% |

2024-11-30 00:01 UTC, elliotchance requested changes

2024-11-30 00:01 UTC, elliotchance commented on orderedmap.go
> +func NewOrderedMap(size ...int) *OrderedMap {
I'm OK with this suggestion, but we shouldn't abuse the constructor like this. Create a `NewOrderedMapWIthCapacity` function.

2024-12-02 15:34 UTC, VarusHsu commented
I have merged it into one commit.

2024-12-04 17:08 UTC, elliotchance approved these changes

2024-12-04 17:10 UTC, merged